# **Data Cleaning**

## Objectives
Clean the dataset, check it for any issues or duplicates.

## Inputs

* Car price dataset
(CarPrice_Assignment.csv) from the Data folder.

## Outputs

* A cleaned and checked car price dataset ready for analysis.

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\liene\\OneDrive\\Documents\\Car Price Analysis\\Car-Prices-Analysis-Project-1\\jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\liene\\OneDrive\\Documents\\Car Price Analysis\\Car-Prices-Analysis-Project-1'

# Check the Dataset

The dataset is cecked for missing values, duplicates and any other issues that may need cleaning.

In [4]:
# import pandas
import pandas as pd

The car price dataset is loaded using Pandas so it can be checked and cleaned.

In [5]:
# Load the car prices dataset
df = pd.read_csv("Data/CarPrice_Assignment.csv")

Check for missing values.

In [7]:
# Check for missing values in the dataset
# code references from LMS
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

### Missing values result.

No missing values were found in the dataset, so no values need to be filled or removed. This was double-checked using Data Wrangler, and it confirms that all columns contain 0% missing values.

### Check for Duplicates.

The dataset is checked for any duplicates in the dataset, that need to be inspected and removed if necessary.

In [8]:
# Check for duplicate rows in the dataset
# code references from LMS
df.duplicated().sum()

0

### Duplicates Result

No duplicates were found in this dataset, so no rows/ uplicates need to be inspected or removed.

### Check data type.

The data types from dataset are checked to make sure they are correct and suiteble for further analysis.

In [9]:
# Check the data types of each column
df.dtypes

car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

### Data Types Results.

The dataset has 3 different data types. int64, float64 and object. They are checked to see if any of them need changing.

### Inspect The Dataset.

The values of each column in the dataset are inspected to see if the data types are suitable.

In [ ]:
# display the first five rows of the dataset.
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [12]:
# Check for dataset information
# code references from LMS
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

### Check Text Columns.

The text columns are checked for any inconsistencies and if they need changing.

In [14]:
# Check the unique values in the text columns
# Code suggested with the assistance from ChatGPT
df.select_dtypes(include='object').nunique()

CarName           147
fueltype            2
aspiration          2
doornumber          2
carbody             5
drivewheel          3
enginelocation      2
enginetype          7
cylindernumber      7
fuelsystem          8
dtype: int64

In [25]:
# Check the most common car names
# code suggested with the assistance from ChatGPT
df['CarName'].value_counts().head(10)

CarName
toyota corona           6
toyota corolla          6
peugeot 504             6
subaru dl               4
mitsubishi mirage g4    3
mazda 626               3
toyota mark ii          3
mitsubishi outlander    3
mitsubishi g4           3
honda civic             3
Name: count, dtype: int64

In [31]:
# Check Audi car names for inconsistencies
# code suggested with assistance of ChatGPT
df[df['CarName'].str.contains('audi')]['CarName'].unique()

array(['audi 100ls', 'audi fox', 'audi 5000', 'audi 4000',
       'audi 5000s (diesel)'], dtype=object)

### Car Name Result

An inconsistency was found in the Audi car names. 'audi  100 ls' and 'audi 100ls' use different formatting and need to be standardised.

In [16]:
# Check the unique values in the fueltype column
# code references from lms
df['fueltype'].unique()

array(['gas', 'diesel'], dtype=object)

In [17]:
# Check the unique values in the aspiration column
df['aspiration'].unique()

array(['std', 'turbo'], dtype=object)

In [18]:
# Check the unique values in the doornumber column
df['doornumber'].unique()

array(['two', 'four'], dtype=object)

In [19]:
# Check the unique values in the carbody column
df['carbody'].unique()

array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object)

In [20]:
# Check the unique values in the drivewheel column
df['drivewheel'].unique()

array(['rwd', 'fwd', '4wd'], dtype=object)

In [21]:
# Check the unique values in the enginelocation column
df['enginelocation'].unique()

array(['front', 'rear'], dtype=object)

In [22]:
# Check the unique values in the enginetype column
df['enginetype'].unique()

array(['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv'], dtype=object)

In [23]:
# Check the unique values in the cylindernumber column
df['cylindernumber'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [24]:
# Check the unique values in the fuelsystem column
df['fuelsystem'].unique()

array(['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi'],
      dtype=object)

## Data Cleaning

During thorough data inspection, a small inconsistency was found in the 'CarName' column. 
The same Audi model appears as both 'audi 100 ls' and 'audi 100ls'.
This will be corrected to so the car name is correct throughout the dataset.

In [34]:
# Correct the misspelled car names in the CarName column.
# Code references from LMS
df['CarName']=df['CarName'].replace('audi 100ls', 'audi 100 ls')

In [35]:
# Check the correct Audi car names after the correction.
df[df['CarName'].str.contains('audi',case=False)]['CarName']

3            audi 100 ls
4            audi 100 ls
5               audi fox
6            audi 100 ls
7              audi 5000
8              audi 4000
9    audi 5000s (diesel)
Name: CarName, dtype: object

The Audi car name was corrected and checked to make sure it is correct and consistent throughout the dataset.

## Check Numerical Values

The numerical columns are checked to see if there are any unusual values or inconsistancies that could need cleaning.

In [36]:
# Check for numerical values in the dataset.
df.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

The numerical values were checked and no obvious inconsistant values stood out in this dataset.

# Push files to Repo

* In cases where you don't need to push files to Repo, you may replace this section with "Conclusions and Next Steps" and state your conclusions and next steps.

In [ ]:
import os
try:
  # create your folder here
  # os.makedirs(name='')
except Exception as e:
  print(e)